#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/home/chisco/.vscode-server/bin/e54c774e0add60467559eb0d1e229c6452cf8447/node" "/home/chisco/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "code --openExternal " "$@"